name: Say hello
on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04 
    steps:
      - name: Echo the message
        run: |
          echo "Hello world"
      - name: Dame la fecha
        run: date
      - run: hostname
      - run: id
      - run: ls -la
