name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-18.04 
    steps:
      - name: Echo the message
        run: |
          echo "Hello world"
      - name: Dame la fecha
        run: date
      - run: hostname
      - run: id

  lint:
    needs: [hello]
    runs-on: ubuntu-18.04 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #- run: ls -la

      #- name: Download latest earthly
      #  run: "sudo /bin/sh -c 'wget -q https://github.com/earthly/earthly/releases/download/v0.6.14/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      #- name: Earthly version
      #  run: earthly --version
      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest" # or pin to an specific version, e.g. "v0.6.10"

      - name: Targets
        run: earthly ls

      - name: Lint
        run: earthly --ci +lint

  tests:
    needs: [hello]
    runs-on: ubuntu-18.04 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #- run: ls -la

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest" # or pin to an specific version, e.g. "v0.6.10"

      - name: Tests
        run: earthly --ci +tests


  build:
    needs: [lint, tests]
    runs-on: ubuntu-18.04 
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest" # or pin to an specific version, e.g. "v0.6.10"

      - name: Build
        #run: earthly --ci +build # TODO fix why save local is disabled
        run: earthly +build
      #- run: ls -la ./build

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build


  docker-image:
    needs: [build]
    runs-on: ubuntu-18.04 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #- run: ls -la

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      #- run: ls -la ./build

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          version: "latest" # or pin to an specific version, e.g. "v0.6.10"

      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"

      - name: Docker
        run: earthly --ci +docker --tag="ghactions"

      #- name: Upload
      #  run: earthly --ci --push +docker --tag="ghactions"
